### ISSUE TITLE
`ytdl-watch-later` and `ytdl-liked` raise `ValueError: '--' is not in list`

### ISSUE THREAD

**Issue by dnicolson** [Tatsh/youtube-unofficial#16]
Reverting https://github.com/Tatsh/youtube-unofficial/commit/3ea9d0f487615611bac450211ee2d70b7b1b6bfb appears to resolve the issue.

**Comment by Tatsh** [comment]
What was the command you were using (minus personal stuff)?

**Comment by dnicolson** [comment]
Just the `ytdl-watch-later` command:

```
$ ytdl-watch-later
Traceback (most recent call last):
  File "/Users/dave/.asdf/installs/python/3.9.0/bin/ytdl-watch-later", line 33, in <module>
    sys.exit(load_entry_point('youtube-unofficial==0.2.0', 'console_scripts', 'ytdl-watch-later')())
  File "/Users/dave/.asdf/installs/python/3.9.0/lib/python3.9/site-packages/youtube_unofficial/downloaders.py", line 92, in download_watch_later
    return download_playlist('WL')
  File "/Users/dave/.asdf/installs/python/3.9.0/lib/python3.9/site-packages/youtube_unofficial/downloaders.py", line 55, in download_playlist
    dd_index = sys.argv.index('--')
ValueError: '--' is not in list
```

**Comment by Tatsh** [comment]
Makes sense. I was catching the wrong exception type assuming it would throw `IndexError` in that case.
