### ISSUE TITLE
KeyError: 'DELEGATED_SESSION_ID'

### ISSUE THREAD

**Issue by kasnder** [Tatsh/youtube-unofficial#18]
Hello,

I'm trying to use your wonderful API, using an extracted cookies file from my Mozilla Firefox.

Unfortunately, I get the following error, when calling `toggle_watch_history`:

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    yt.toggle_watch_history()
  File "/home/konrad/.local/lib/python3.8/site-packages/youtube_unofficial/__init__.py", line 487, in toggle_watch_history
    return self._toggle_history(WATCH_HISTORY_URL, 3)
  File "/home/konrad/.local/lib/python3.8/site-packages/youtube_unofficial/__init__.py", line 476, in _toggle_history
    return self._single_feedback_api_call(
  File "/home/konrad/.local/lib/python3.8/site-packages/youtube_unofficial/__init__.py", line 459, in _single_feedback_api_call
    user=dict(onBehalfOfUser=ytcfg['DELEGATED_SESSION_ID'])),
KeyError: 'DELEGATED_SESSION_ID'
```

**Comment by kasnder** [comment]
The provided PR fixes this for me.
