### ISSUE TITLE
Not Found for url: https://www.youtube.com/service_ajax?name=feedbackEndpoint

### ISSUE THREAD

**Issue by kasnder** [Tatsh/youtube-unofficial#19]
When trying to delete videos from the watch history (`remove_video_ids_from_history`), I get the following the following error:

```
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    print(yt.remove_video_ids_from_history([entries[0]['videoRenderer']['videoId']]))
  File "/home/konrad/.local/lib/python3.8/site-packages/youtube_unofficial/__init__.py", line 409, in remove_video_ids_from_history
    self._download_page(
  File "/home/konrad/.local/lib/python3.8/site-packages/youtube_unofficial/download.py", line 43, in _download_page
    return download_page(self._sess, url, data, method, headers, params,
  File "/home/konrad/.local/lib/python3.8/site-packages/youtube_unofficial/download.py", line 25, in download_page
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://www.youtube.com/service_ajax?name=feedbackEndpoint
```

**Comment by Tatsh** [comment]
Reopening because playlist management is still affected by this. History was fixed.
